print "How many minutes do New Yorkers lose every year because they put on and take off coats all the time?"
print "Assumptions:"
print "# of New Yorkers in New York City = 8,000,000"
print "# of times each New Yorker puts on / take off coats per day = 3 times a day"
print "time it takes to put on / take off coats = 3 minutes"
print "# of days per year that New Yorkers need to have coats = 100"
print 8000000.0 * 3 * 3 * 100, " minutes lost to putting on and taking off coats in NYC."